### ISSUE TITLE
stream is undefined error

### ISSUE THREAD

**Issue by moimael** [substack/stream-browserify#11]
Hi,

I try to use a dependency made for nodejs called tilelive. This dependency require stream.

I use browserify + gulp as my build tools but every time I launch my app and require tilelive I get : 
```stream is undefined``` error. I tried to install manually stream-browserify in my project, and also in tilelive directory, nothing works.

Any ideas ?

Thanks :)

**Comment by stevemao** [comment]
Can you share your code that triggers this? Or even better, send a PR with fail test.
